In [9]:
import torch
from einops import rearrange

In [41]:
t = torch.randn((2, 4, 4))
t

tensor([[[-0.1543, -1.2521,  1.0757,  0.2622],
         [ 2.1931,  0.7439, -0.1593, -1.1349],
         [-0.3910, -0.7182, -0.8423, -0.0105],
         [ 2.2345,  1.2266,  0.6552,  0.2163]],

        [[-0.4925,  0.1306, -1.3880, -0.4210],
         [ 0.0689, -0.2506, -0.8133, -0.9010],
         [ 0.2638,  0.2530, -0.1458, -0.3685],
         [ 1.5330, -0.4969, -0.5336, -0.9903]]])

In [49]:
mask = torch.tensor([[1, 1, 1, 0],
                     [1, 1, 0, 0]])
mask

tensor([[1, 1, 1, 0],
        [1, 1, 0, 0]])

In [59]:
mask2 = torch.matmul(rearrange(mask[0], 'b -> b 1'), rearrange(mask[0], 'b -> 1 b'))
mask2

tensor([[1, 1, 1, 0],
        [1, 1, 1, 0],
        [1, 1, 1, 0],
        [0, 0, 0, 0]])

In [60]:
mask3 = torch.matmul(rearrange(mask[1], 'b -> b 1'), rearrange(mask[1], 'b -> 1 b'))
mask3

tensor([[1, 1, 0, 0],
        [1, 1, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [70]:
new_mask = torch.cat([mask2, mask3], 0)

In [72]:
new_mask = rearrange(new_mask, '(b s) d -> b s d', b=2)
new_mask

tensor([[[1, 1, 1, 0],
         [1, 1, 1, 0],
         [1, 1, 1, 0],
         [0, 0, 0, 0]],

        [[1, 1, 0, 0],
         [1, 1, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]])

In [73]:
new_mask.shape

torch.Size([2, 4, 4])

In [50]:
mask_bool = mask == 0
mask_bool

tensor([[False, False, False,  True],
        [False, False,  True,  True]])

In [74]:
new_mask_bool = new_mask == 0
new_mask_bool

tensor([[[False, False, False,  True],
         [False, False, False,  True],
         [False, False, False,  True],
         [ True,  True,  True,  True]],

        [[False, False,  True,  True],
         [False, False,  True,  True],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]])

In [51]:
mask_bool = rearrange(mask_bool, 'b s -> b 1 s ')

In [52]:
mask_bool.shape

torch.Size([2, 1, 4])

In [53]:
t_ = t.masked_fill(mask_bool, -1e9)
t_

tensor([[[-1.5431e-01, -1.2521e+00,  1.0757e+00, -1.0000e+09],
         [ 2.1931e+00,  7.4388e-01, -1.5934e-01, -1.0000e+09],
         [-3.9102e-01, -7.1816e-01, -8.4231e-01, -1.0000e+09],
         [ 2.2345e+00,  1.2266e+00,  6.5523e-01, -1.0000e+09]],

        [[-4.9246e-01,  1.3059e-01, -1.0000e+09, -1.0000e+09],
         [ 6.8946e-02, -2.5058e-01, -1.0000e+09, -1.0000e+09],
         [ 2.6384e-01,  2.5302e-01, -1.0000e+09, -1.0000e+09],
         [ 1.5330e+00, -4.9691e-01, -1.0000e+09, -1.0000e+09]]])

In [78]:
t_.shape

torch.Size([2, 4, 4])

In [75]:
new_t = t.masked_fill(new_mask_bool, -1e9)
new_t

tensor([[[-1.5431e-01, -1.2521e+00,  1.0757e+00, -1.0000e+09],
         [ 2.1931e+00,  7.4388e-01, -1.5934e-01, -1.0000e+09],
         [-3.9102e-01, -7.1816e-01, -8.4231e-01, -1.0000e+09],
         [-1.0000e+09, -1.0000e+09, -1.0000e+09, -1.0000e+09]],

        [[-4.9246e-01,  1.3059e-01, -1.0000e+09, -1.0000e+09],
         [ 6.8946e-02, -2.5058e-01, -1.0000e+09, -1.0000e+09],
         [-1.0000e+09, -1.0000e+09, -1.0000e+09, -1.0000e+09],
         [-1.0000e+09, -1.0000e+09, -1.0000e+09, -1.0000e+09]]])

In [82]:
value = torch.randn(size=(2, 4, 5))
value

tensor([[[-0.4415, -0.0605,  0.8589,  0.7689, -0.6676],
         [ 1.0560,  0.1637, -1.4993, -1.0977, -0.3597],
         [ 1.0901, -0.7723,  0.5849,  1.3764,  0.3691],
         [-1.5408, -0.2936,  1.8331, -0.2097,  0.7592]],

        [[ 1.0063,  1.2804,  1.0638,  0.8085, -0.0765],
         [-0.7015,  0.2348,  0.6436,  1.4058,  0.4843],
         [ 0.2197, -0.0321,  0.9020,  0.3394, -0.8406],
         [-0.2490,  0.5921,  0.6787, -1.4766,  0.3405]]])

In [83]:
value.shape

torch.Size([2, 4, 5])

In [89]:
value

tensor([[[-0.4415, -0.0605,  0.8589,  0.7689, -0.6676],
         [ 1.0560,  0.1637, -1.4993, -1.0977, -0.3597],
         [ 1.0901, -0.7723,  0.5849,  1.3764,  0.3691],
         [-1.5408, -0.2936,  1.8331, -0.2097,  0.7592]],

        [[ 1.0063,  1.2804,  1.0638,  0.8085, -0.0765],
         [-0.7015,  0.2348,  0.6436,  1.4058,  0.4843],
         [ 0.2197, -0.0321,  0.9020,  0.3394, -0.8406],
         [-0.2490,  0.5921,  0.6787, -1.4766,  0.3405]]])

In [87]:
result1 = torch.matmul(torch.softmax(t_, -1), value)
result1

tensor([[[ 0.7656, -0.5569,  0.4963,  1.0751,  0.0999],
         [-0.0676, -0.0718,  0.4231,  0.4828, -0.5391],
         [ 0.4301, -0.1842,  0.0638,  0.3622, -0.2934],
         [ 0.1073, -0.1018,  0.2751,  0.4149, -0.4600]],

        [[-0.1054,  0.5998,  0.7903,  1.1973,  0.2885],
         [ 0.2877,  0.8404,  0.8870,  1.0599,  0.1595],
         [ 0.1570,  0.7604,  0.8548,  1.1056,  0.2024],
         [ 0.8080,  1.1590,  1.0150,  0.8779, -0.0114]]])

In [88]:
result2 = torch.matmul(torch.softmax(new_t, -1), value)
result2

tensor([[[ 0.7656, -0.5569,  0.4963,  1.0751,  0.0999],
         [-0.0676, -0.0718,  0.4231,  0.4828, -0.5391],
         [ 0.4301, -0.1842,  0.0638,  0.3622, -0.2934],
         [ 0.0410, -0.2407,  0.4444,  0.2095,  0.0253]],

        [[-0.1054,  0.5998,  0.7903,  1.1973,  0.2885],
         [ 0.2877,  0.8404,  0.8870,  1.0599,  0.1595],
         [ 0.0689,  0.5188,  0.8220,  0.2693, -0.0231],
         [ 0.0689,  0.5188,  0.8220,  0.2693, -0.0231]]])